const types = {
  LIST_UPDATED_TEXT: 'LIST_UPDATED_TEXT',
  LIST_UPDATED: 'LIST_UPDATED',
  LIST_ADDED_ITEM: 'LIST_ADDED_ITEM',
  REGISTRATION_USER_REGISTERED: 'REGISTRATION_USER_REGISTERED',
  LOGIN_USER_AUTHENTICATED: 'LOGIN_USER_AUTHENTICATED',
  LOGIN_ERROR_OCURRED: 'LOGIN_ERROR_OCURRED',
  LISTS_LOADED: 'LISTS_LOADED',
  LISTS_SELECTED_LIST: 'LISTS_SELECTED_LIST',
  LISTS_UPDATED_TEXT: 'LISTS_UPDATED_TEXT',
  REGISTRATION_ERROR_OCURRED: 'REGISTRATION_ERROR_OCURRED',
};

export default types;
