const types = {
  UPDATE_TEXT: 'UPDATE_TEXT',
  LIST_UPDATED: 'LIST_UPDATED',
  LIST_ADDED_ITEM: 'LIST_ADDED_ITEM',
  LOGIN_UPDATE_USERNAME: 'LOGIN_UPDATE_USERNAME',
  LOGIN_AUTHENTICATED: 'LOGIN_AUTHENTICATED',
  LISTS_LOADED: 'LISTS_LOADED',
  LISTS_SELECTED: 'LISTS_SELECTED',
  LISTS_TEXT_UPDATED: 'LISTS_TEXT_UPDATED',
};

export default types;
