const types = {
  LIST_UPDATED_TEXT: 'LIST_UPDATED_TEXT',
  LIST_UPDATED: 'LIST_UPDATED',
  LIST_ADDED_ITEM: 'LIST_ADDED_ITEM',
  LOGIN_UPDATED_USERNAME: 'LOGIN_UPDATED_USERNAME',
  LOGIN_AUTHENTICATED: 'LOGIN_AUTHENTICATED',
  LISTS_LOADED: 'LISTS_LOADED',
  LISTS_SELECTED_LIST: 'LISTS_SELECTED_LIST',
  LISTS_UPDATED_TEXT: 'LISTS_UPDATED_TEXT',
};

export default types;
